version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: creator-platform-server
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: mongodb://admin:password123@mongo:27017/creator-platform?authSource=admin
      # Allow frontend (served on host:3000) to access the API
      CLIENT_URL: ${CLIENT_URL}
      JWT_SECRET: ${JWT_SECRET}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    depends_on:
      - mongo

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: creator-platform-client
    ports:
      - "3000:80"
    depends_on:
      - server

volumes:
  mongo-data: